# Writes nnt_build_info.hpp (only when its content changes, so nothing is
# rebuilt needlessly). Inputs: SOURCE_DIR, OUTPUT, BUILD_TYPE, NATIVE.
execute_process(COMMAND git rev-parse --short=12 HEAD
                WORKING_DIRECTORY ${SOURCE_DIR}
                OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE
                RESULT_VARIABLE result ERROR_QUIET)
if(NOT result EQUAL 0)
    set(commit "unknown")
endif()
execute_process(COMMAND git status --porcelain --untracked-files=no
                WORKING_DIRECTORY ${SOURCE_DIR}
                OUTPUT_VARIABLE status RESULT_VARIABLE result ERROR_QUIET)
if(result EQUAL 0 AND NOT status STREQUAL "")
    set(dirty "true")
else()
    set(dirty "false")
endif()
if(NATIVE)
    set(native "true")
else()
    set(native "false")
endif()
if(BUILD_TYPE STREQUAL "")
    set(BUILD_TYPE "unspecified")
endif()

set(content "// Generated by NNtesting/cmake/build_info.cmake - do not edit.
#pragma once
#define NNT_GIT_COMMIT \"${commit}\"
#define NNT_GIT_DIRTY ${dirty}
#define NNT_BUILD_TYPE \"${BUILD_TYPE}\"
#define NNT_NATIVE ${native}
")
if(EXISTS ${OUTPUT})
    file(READ ${OUTPUT} old)
else()
    set(old "")
endif()
if(NOT old STREQUAL content)
    file(WRITE ${OUTPUT} "${content}")
endif()
